version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-nest-app
    overwrite: yes

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall: # LifeCycle Event Hook의 이름을 의미합니다.
    - location: scripts/execute.sh # 스크립트의 위치입니다. files.destination에 정의한 경로에 대한 상대경로롤 작성해주세요.
      timeout: 600 # 스크립트 실행시, 여기에 지정된 시간을 초과하면 안됩니다. 최대 3600초입니다.
      runas: ubuntu # 스크립트 실행 시 가장하는 사용자입니다.
